# Generated by Django 3.2.8 on 2022-01-14 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std_registration',
            old_name='block',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='std_registration',
            old_name='gp',
            new_name='sem',
        ),
        migrations.RenameField(
            model_name='std_registration',
            old_name='vaccinetype',
            new_name='year',
        ),
        migrations.AddField(
            model_name='std_registration',
            name='rollno',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
